<a href="https://colab.research.google.com/github/kamranshahid56-tech/Python_Practice-Numpy-Pandas-/blob/main/Python_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
arr = np.arange(10,50)
print("Original Array")
print(arr)

Original Array
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [4]:
reversed_arr = arr[:: -1]
print("Reversed Array")
print(reversed_arr)
#

Reversed Array
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [5]:
even_arr = arr[arr % 2 == 0]
print("Even Numbers")
print(even_arr)

Even Numbers
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [6]:
even_arr = arr[::2]
print("Even Numbers")
print(even_arr)

Even Numbers
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [7]:
#reshape
arr = np.arange(10,30)
print("Original Array")
print(arr)

Original Array
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [8]:
arr.reshape(4,5)

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [9]:
#reshape use
image = np.random.randint(0,256,(4,4,4))
print("Original Image")
print(image)

Original Image
[[[ 35  61 212 180]
  [213 128 122 165]
  [ 76  81  13   7]
  [235  39  21 184]]

 [[222  91 101 134]
  [170  41 203 236]
  [166 145 226 225]
  [ 25 244 249  71]]

 [[219 102 123  96]
  [176 248  57 245]
  [ 46 236 244 235]
  [115 161 145 176]]

 [[132 170  27 122]
  [117 182 234 198]
  [255 143 151 102]
  [ 19 149 201 214]]]


In [10]:
flattened = image.flatten()
print("Flattened Image")
print(flattened)

Flattened Image
[ 35  61 212 180 213 128 122 165  76  81  13   7 235  39  21 184 222  91
 101 134 170  41 203 236 166 145 226 225  25 244 249  71 219 102 123  96
 176 248  57 245  46 236 244 235 115 161 145 176 132 170  27 122 117 182
 234 198 255 143 151 102  19 149 201 214]


In [11]:
normalized = image/255
print("Normalized Image")
print(normalized)

Normalized Image
[[[0.1372549  0.23921569 0.83137255 0.70588235]
  [0.83529412 0.50196078 0.47843137 0.64705882]
  [0.29803922 0.31764706 0.05098039 0.02745098]
  [0.92156863 0.15294118 0.08235294 0.72156863]]

 [[0.87058824 0.35686275 0.39607843 0.5254902 ]
  [0.66666667 0.16078431 0.79607843 0.9254902 ]
  [0.65098039 0.56862745 0.88627451 0.88235294]
  [0.09803922 0.95686275 0.97647059 0.27843137]]

 [[0.85882353 0.4        0.48235294 0.37647059]
  [0.69019608 0.97254902 0.22352941 0.96078431]
  [0.18039216 0.9254902  0.95686275 0.92156863]
  [0.45098039 0.63137255 0.56862745 0.69019608]]

 [[0.51764706 0.66666667 0.10588235 0.47843137]
  [0.45882353 0.71372549 0.91764706 0.77647059]
  [1.         0.56078431 0.59215686 0.4       ]
  [0.0745098  0.58431373 0.78823529 0.83921569]]]


In [12]:
arr = np.random.randint(0,100,(5,5))
print("Original Array")
print(arr)
#

Original Array
[[ 3 67 96 14 59]
 [98 50 76 10 36]
 [42 75 82 91 79]
 [15 56 44 19 18]
 [52 34 81 26 32]]


In [13]:
arr[arr<50] = 0
print("modified_arr:")
print(arr)

modified_arr:
[[ 0 67 96  0 59]
 [98 50 76  0  0]
 [ 0 75 82 91 79]
 [ 0 56  0  0  0]
 [52  0 81  0  0]]


In [14]:
#create identity matrix
identity = np.eye(5)
print("Identity Matrix")
print(identity)

Identity Matrix
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [15]:
identity[identity == 0] = 2
print("Modified Identity Matrix")
print(identity)

Modified Identity Matrix
[[1. 2. 2. 2. 2.]
 [2. 1. 2. 2. 2.]
 [2. 2. 1. 2. 2.]
 [2. 2. 2. 1. 2.]
 [2. 2. 2. 2. 1.]]


In [16]:
import pandas as pd

In [17]:
Data = {
    "Name" : ["Kamran", "Asim", "Holly"],
    "Age" : [21, 19, 12],
    "Fruit" : ["Banana", "Tenda", "Kiwi"]
}

In [18]:
df = pd.DataFrame(Data)
print("Initial DataFrame")
print(df)

Initial DataFrame
     Name  Age   Fruit
0  Kamran   21  Banana
1    Asim   19   Tenda
2   Holly   12    Kiwi


In [19]:
new_row = pd.DataFrame({
    "Name" : ["Ali"],
    "Age" : [20],
    "Fruit" : ["Apple"]
})
df = pd.concat([df, new_row],ignore_index= True)
print("\nModified DataFrame")
print(df)


Modified DataFrame
     Name  Age   Fruit
0  Kamran   21  Banana
1    Asim   19   Tenda
2   Holly   12    Kiwi
3     Ali   20   Apple


In [20]:
Data = {
    "Name" : ["Kamran", "Asim", "Holly"],
    "Age" : [21, 19, 12],
    "Fruit" : ["Banana", "Tenda", "Kiwi"]
}
df = pd.DataFrame(Data)
print("Initial DataFrame")
print(df)

Initial DataFrame
     Name  Age   Fruit
0  Kamran   21  Banana
1    Asim   19   Tenda
2   Holly   12    Kiwi


In [21]:
df["Age_in_months"] = df['Age']*12
# df = df.drop(columns = ["Age"], axis = 1)
print("\nModified DataFrame")
print(df)


Modified DataFrame
     Name  Age   Fruit  Age_in_months
0  Kamran   21  Banana            252
1    Asim   19   Tenda            228
2   Holly   12    Kiwi            144


In [22]:
df.insert(1, "Age_in_days", df["Age_in_months"]*30)
print("\nModified DataFrame")
print(df)


Modified DataFrame
     Name  Age_in_days  Age   Fruit  Age_in_months
0  Kamran         7560   21  Banana            252
1    Asim         6840   19   Tenda            228
2   Holly         4320   12    Kiwi            144


In [23]:
df['Age'].mean()

np.float64(17.333333333333332)

In [24]:
df['Age_in_days'].max()

7560

In [25]:
df['Age_in_months'].std()

56.7097875150313

In [26]:
df["Age"].describe()

count     3.000000
mean     17.333333
std       4.725816
min      12.000000
25%      15.500000
50%      19.000000
75%      20.000000
max      21.000000
Name: Age, dtype: float64

In [34]:
arr = np.random.rand(5,3)
print(arr)

[[0.81642518 0.91928654 0.65406809]
 [0.79481785 0.01713653 0.11724111]
 [0.94826384 0.70401623 0.50072852]
 [0.86033869 0.29395498 0.87643567]
 [0.12744    0.57500734 0.80885033]]


In [35]:
df = pd.DataFrame(arr)

In [36]:
print(df)

          0         1         2
0  0.816425  0.919287  0.654068
1  0.794818  0.017137  0.117241
2  0.948264  0.704016  0.500729
3  0.860339  0.293955  0.876436
4  0.127440  0.575007  0.808850


In [37]:
arr = np.random.rand(5,3)
print(arr)

[[0.05284318 0.72855592 0.11450153]
 [0.66256389 0.40715923 0.35467642]
 [0.59330253 0.79738883 0.47458362]
 [0.32023816 0.45800931 0.38305226]
 [0.29537214 0.82749    0.84683472]]


In [42]:
df1 = pd.DataFrame(arr, columns = ["A", "B", "C"])
df1 = df1.round(2)
print(df1)

      A     B     C
0  0.05  0.73  0.11
1  0.66  0.41  0.35
2  0.59  0.80  0.47
3  0.32  0.46  0.38
4  0.30  0.83  0.85


In [46]:
Data = {
    'Name' : ["Kamran", "Asim", "Holly"],
    'Age' : [21, 19, 12],
}

In [47]:
df = pd.DataFrame(Data)

In [51]:
df.sort_values(by = "Age", ascending = False, inplace = True)
print(df)

     Name  Age
0  Kamran   21
1    Asim   19
2   Holly   12


In [56]:
# Task 1
arr = np.random.randint(1,100,(10,5))
print(arr)

[[46 62 89 22 51]
 [79 83 93 11 98]
 [96 58 41 56 27]
 [43 33 59 70 28]
 [39 97  1 82  5]
 [32 24 17  9 70]
 [86 81 41  2 53]
 [86 83 79 51 81]
 [60 51 55 84 17]
 [70 66 51 88 83]]


In [75]:
mean = np.mean(arr, axis = 1)
mean = mean.reshape(10,1)
mean = mean.round(0)
print(mean)

[[54.]
 [73.]
 [56.]
 [47.]
 [45.]
 [30.]
 [53.]
 [76.]
 [53.]
 [72.]]


In [82]:
std = np.std(arr, axis = 1)
std = std.reshape(10,1)
std = std.round(0)
print(std)

[[22.]
 [32.]
 [23.]
 [16.]
 [39.]
 [21.]
 [30.]
 [13.]
 [22.]
 [13.]]


In [83]:
normalized = (arr-mean)/std
# normalized = normalized.round(0)
print(normalized)

[[-0.36363636  0.36363636  1.59090909 -1.45454545 -0.13636364]
 [ 0.1875      0.3125      0.625      -1.9375      0.78125   ]
 [ 1.73913043  0.08695652 -0.65217391  0.         -1.26086957]
 [-0.25       -0.875       0.75        1.4375     -1.1875    ]
 [-0.15384615  1.33333333 -1.12820513  0.94871795 -1.02564103]
 [ 0.0952381  -0.28571429 -0.61904762 -1.          1.9047619 ]
 [ 1.1         0.93333333 -0.4        -1.7         0.        ]
 [ 0.76923077  0.53846154  0.23076923 -1.92307692  0.38461538]
 [ 0.31818182 -0.09090909  0.09090909  1.40909091 -1.63636364]
 [-0.15384615 -0.46153846 -1.61538462  1.23076923  0.84615385]]
